version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

  info_handler:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: simple
    filename: jumbler.log
    when: midnight
    interval: 1
    encoding: utf8

  debug_handler:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: jumbler-debug.log
    when: midnight
    interval: 1
    encoding: utf8

loggers:
  jumbler:
    level: DEBUG
    handlers: [console, info_handler, debug_handler]
    propagate: no

  asyncio:
    level: WARNING
    handlers: [console, info_handler, debug_handler]
    propagate: no

root:
  level: INFO
  handlers: [console, info_handler, debug_handler]